name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          app/build
          app/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Generate Gradle wrapper
      run: ./gradlew wrapper

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # TODO: Add your signing key and password as secrets in your repository settings
    # - name: Sign APK
    #   uses: r0adkll/sign-android-release@v1
    #   with:
    #     releaseDirectory: app/build/outputs/apk/release
    #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
    #     alias: ${{ secrets.ALIAS }}
    #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #     keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload a release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
